services:

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  rest_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/emails
    depends_on:
      - mongodb

volumes:
  mongo:
