stages:

  preprocess:
    cmd: python3 src/training/preprocess.py
    deps:
      - src/training/preprocess.py
      - inputs/data.csv
    outs:
      - artifacts/data.json
      - artifacts/tag2idx.json

  retrain:
    cmd: python3 src/training/train.py
    deps:
      - artifacts/data.json
      - artifacts/tag2idx.json
    outs:
      - artifacts/model_config.json
      - artifacts/vectorizer.pkl
      - artifacts/model.pt
      - artifacts/distribution.pkl
  